apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-app
          image: yavuzozbay/nodejs-app:1.0.0 
          env:
      - name: PORT
        valueFrom:
          secretKeyRef:
            name: mydatabase-secret
            key: PORT
      - name: MYSQL_HOST
        valueFrom:
          secretKeyRef:
            name: mydatabase-secret
            key: MYSQL_HOST
      - name: MYSQL_USER
        valueFrom:
          secretKeyRef:
            name: mydatabase-secret
            key: MYSQL_USER
      - name: MYSQL_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mydatabase-secret
            key: MYSQL_PASSWORD
      - name: MYSQL_DATABASE
        valueFrom:
          secretKeyRef:
            name: mydatabase-secret
            key: MYSQL_DATABASE
    ports:
      - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-service
spec:
  selector:
    app: nodejs-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
