apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-app
          image: yavuzozbay/nodejs-app:1.0.0 
          env:
            - name: PORT
              value: "3000" 
            - name: MYSQL_HOST
              value: "mysql-service" 
            - name: MYSQL_USER
              value: "root" 
            - name: MYSQL_PASSWORD
              value: "aswq" 
            - name: MYSQL_DATABASE
              value: "mydatabase" 
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-service
spec:
  selector:
    app: nodejs-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer